### PR TITLE
1-loop SMEFT-WET matching

### PR DESCRIPTION
**Pull request by DavidMStraub**
@jasonaebischerGIT @jackypheno: comments and checks welcome. @peterstangl, @avelino3000, @jvirto, maybe you have comments, too.

Work in progress: this implements the 1-loop SMEFT-WET matching from https://arxiv.org/abs/1908.05295.

## Strategy

Step 1: Replacing the old tree-level matching (typed by hand from https://arxiv.org/abs/1709.04486) by a new one based on a Pythonization of the notebook provided by the authors of the new paper. This serves as a validation of the Pythonization. And it works! A unit test was added along with the old code.

Step 2: Adding the 1-loop matching. This is hard to test since we have no alternative implementation to compare to, but a simple cross-check is that the resulting WET WCs have the right symmetries. This currently fails for the operator `VddLL`, but works for all others. Need to investigate.

## Profiling

The new implementation of the tree-level matching is a factor of 3 slower than before (3 ms vs 1 ms). This is mostly due to explicit appearance of linearized Wilson coefficients affecting SM couplings instead of writing it in terms of the effective couplings as done in the old paper, which leads to longer expressions.

The 1-loop matching is, expectedly, **very** slow, O(0.5 s). This could be accelerated significantly in the future by precomputing the coefficients numerically (for fixed parameters and matching scale).

## Interface

Obviously the user must be given the option to change the matching scale and to switch 1-loop contributions on/off. In Wilson, this could be done via `set_config`. However, the matching itself is usually done via the `wcxf` method `WC.match(parameters)`, where `parameters` was originally meant for parameters like masses and couplings. Should we abuse this for the matching scale and a boolean switch for the loop contributions as well? Or should we just choose a default and make it configurable only via `Wilson`?

In the end, maybe it was not such a good idea after all to make `match` part of `wcxf`, since it is not a simple basis manipulation like `translate`.

### CODE REVIEW

**Comment by jackypheno** [comment]
Hi David,

Great thanks !! OK, I will play with it and let you know if I have any comment.

**Comment by DavidMStraub** [comment]
The problem with the incorrect symmetry for `VddLL` is now solved. Apart from fixing the interface (as discussed above), what is missing now is a few numerical cross-checks against the Mathematica code to be absolutely sure everything is correct.

**Comment by DavidMStraub** [comment]
Concerning the interface: maybe it's time to merge `wcxf-python` in wilson as suggested some time ago by @peterstangl, what do you think?

**Comment by DavidMStraub** [comment]
FYI I started adding unit tests. A lot of them already pass, but there are still issues with dipoles (which is the only place where masses matter, so this is probably the problem) and with `phil3` contributing to 4-fermions. Debugging.

**Comment by DavidMStraub** [comment]
Concerning the interface: my current tendency would be indeed to add the loop level (tree vs. 1-loop) as a parameter to the matching function. In Wilson, this could then be set globally via a config option. The matching scale, instead, is not needed as I realized: it is already an argument of the matching function and moreover is known: it is simply `WC.scale`.

**Comment by DavidMStraub** [comment]
OK, so I implemented it like this:

- When using `WC.match`, 1-loop contributions are off by default and need to be switch on by setting the parameter `loop_order`:
```python
wc = wcxf.WC(..., eft='SMEFT')
wc.match('WET', 'flavio', parameters={'loop_order': 1})
```
This is admittedly a bit clumsy but we any don't want the users to directly use `wcxf`, do we.
- When using Wilson, there is a new config option:
```python
w = Wilson(..., eft='SMEFT')
w.set_option('smeft_matching_order', 1)
w.match_run(...)
```
Note that, in all cases, loop contributions are off by default. Do you agree with this default?

If there are no further comments, I plan to **merge this and release** a new wilson version.

**Pull request merged**
