### PR TITLE
use voluptuous schemas to restrict option values

### PR DESCRIPTION
**Pull request by peterstangl**
@DavidMStraub this is a first try of implementing restricted options using voluptuous schemas. The checks of both keys and values are performed in `set_option` as well as in `set_default_option`.
The restrictions have to be specified as class attribute `_restricted_options` in terms of a voluptuous schemas dictionary. For any key in `_default_options` that is not present in `_restricted_options`, all values are allowed. Any key in `_restricted_options` that is not in `_default_options` is ignored.

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Thanks! I made some changes: since the main point of the schema is to validate the input, I think the methods `_option_check_key` and `_option_check_key_value` can be done away with. Now the schema is defined on class instantiation (rather than on every single check) and the `set_option` is piped through voluptuous to get the config dict in the right format.

**Comment by peterstangl** [comment]
Yes that's a good idea to do away with the `_option_check_key` and `_option_check_key_value` methods. Of course `get_options` does not need any validation as there will be an error anyway if a key is used that is not in `self._options`.

However, I thought that validating the input to `set_default_options` is in principle as important as validating it for `set_options`. This was actually the reason, why I decided to not define the schema on instantiation but to save it in a class attribute the first time it is used by any of the instances or by the class itself. It was actually not defined on every single check, but only once for the class and all instances at the same time on the very first check. The fact that the schema only had to be defined once for the whole class and it was possible to use it also for the class method `set_default_options` was why I thought this was the better solution than defining the schema again on every instantiation and then only being able to use it for the instance method `set_options`.

I also do not understand the following changes:

Why is the whole options dictionary copied and completely revalidated each time instead of just passing the changed key-value-pair to the schema for validation? So what is the advantage of the piping instead of just using the schema for validation and then setting the new value if there is no error?

Why do you use
```python
options[vol.Required(k, default=self._default_options[k])] = self._restricted_options[k]
```
instead of  just
```python
options[k] = self._restricted_options[k]
```
As far as I see, there would only be a difference between those two options if a dictionary is passed to the schema that is missing the key `k`. Using the piping, however, I think this cannot happen by construction as the whole options dictionary is copied beforehand and always contains the key `k`.

Why is the new function `set_options` introduced? As far as I can see, it is only called inside the `set_option` function and the one line of code in `set_options` could also be put just into the `set_option` function instead of the function call to `set_options`.


So I would suggest to store the defined schema in a class attribute instead of an instance attribute such that it can also be used in `set_default_options`. This is done in my latest commit.
For now, I have kept most of the other changes I do not fully understand (except for the `set_options` function), but I would think that using the schema for mere validation of the changed key-value-pair is enough and that it is not necessary to copy the whole options dictionary each time to pipe it through voluptuous.

**Comment by DavidMStraub** [comment]
Before going into details, one thing I don't understand: if the default option dict changes but the schema has already been saved as a class attribute, doesn't the schema still contain the outdated default values?

**Comment by peterstangl** [comment]
At the moment, yes, the schema would still contain the outdated default values. To avoid this, one would need to run `get_schema` again and update the class attribute each time the default values are changed. However, I think the default values in the schema don't have any effect in the current implementation and one could also define the schema without default values. Or am I missing something?

**Comment by DavidMStraub** [comment]
In my previous implementation, it did have an effect, namely setting the default values in the schema at the time of instantiation. This was the reason for putting it in `__init__`.

But indeed getting rid of this should simplify things a lot. Let me give it a try.

**Comment by DavidMStraub** [comment]
OK now I think it makes much more sense. The default options are now separated from the schema and are only used for `get_option` and for initializing `_config`. The schema can instead now be a constant class attribute and is used to validate the options and default options. By treating all options as optional, it is also possible to validate individual values as you mentioned.

By the way, concerning the "piping": this can be useful when voluptuous is used to "coerce" input values to certain types or formats if necessary. We currently don't need this, but it can be useful when reading values from a config file etc.

**Comment by peterstangl** [comment]
Yes, I think that's a very good solution now. I also agree that the piping makes much sense when reading values from external sources.
In contrast to the previous versions, it is now required to manually define an entry in the option schema for each default option, but I think that's actually useful to be that strict.
I have extended the tests to check in all subclasses of `ConfigurableClass` that there is actually a default option defined for each entry in the option schema.

**Pull request merged**
