### PR TITLE
Option interface: 1st try (WIP)

### PR DESCRIPTION
**Pull request by DavidMStraub**
Motivated by #13.

@peterstangl, the `set_option`/`get_option` methods are motivated by `pandas`... do you find the interface intuitive?

### CODE REVIEW

**Comment by peterstangl** [comment]
Sorry, I missed that `set_default_option` is a class method. But perhaps in that case, one could call it something like `with_default_option` since it can be used to construct Wilson instances *with* the specified default option. This would perhaps make the distinction from the `set_option` method clearer and possibly avoid some confusion (that I had...).

**Comment by DavidMStraub** [comment]
Basically when `set_default_option` is called, the default options are modified, which are a class property. This means that they will be changed for all future instance of `Wilson`. Use case: say you want to perform your analysis always with a specific value of some input parameter. Rather than having to call `set_option` on each and every instance after instantiating it, you could then simply call

```python
import wilson
wilson.Wilson.set_default_option(...)
```
and no longer worry about it.

The problem I can see with this is that `set_default_option` can also be called on the instance, not just on the class, which might indeed be confusing as it affects the class, not just the instance. Not sure how to prevent that ...

**Comment by DavidMStraub** [comment]
Good point. At first I thought it would be better to also change existing instances, but this is indeed problematic since they will have cached results with the old default parameters. Good idea to call `set_option` in init.

**Comment by DavidMStraub** [comment]
OK done. Can you please rebase #13 onto this branch?

**Comment by DavidMStraub** [comment]
OK let's work with this interface, the config validation can be added later.

**Pull request merged**
