### PR TITLE
Fix two problem discussed in issue #75

### PR DESCRIPTION
**Pull request by dvandyk**
- trigger workflow also on created releases
 - test installation of the freshly-built wheel prior to deployment

### CODE REVIEW

**Comment by jasonaebischerGIT** [comment]
So, how should is a new version release now? Is it done automatically, or is it done with twine still?

**Comment by dvandyk** [comment]
> So, how should is a new version release now? Is it done automatically, or is it done with twine still?

If you create a new release through the github interface, it will trigger deploying if the following two conditions are fulfilled:
 1. You need to setup the username and password to push to PyPI as (https://docs.github.com/en/actions/reference/encrypted-secrets)[repository secrets] with the following two **case sensitive** names:
   - ``TWINE_USERNAME``
   - ``TWINE_PASSWORD``
 2. The release is associated with a tag starting with ``v``. There will always be a tag, AFAIK, but you need to name it e.g. ``v2.2``, ``v2.2.1``, etc.

Is condition #2 fulfilled yet? I cannot check it.

**Comment by DavidMStraub** [comment]
> Is condition #2 fulfilled yet? I cannot check it.

Yes. https://github.com/wilson-eft/wilson/tags

**Comment by dvandyk** [comment]
Sorry, embarrassing typo, meant #1 of course!

**Comment by DavidMStraub** [comment]
Oh OK. No, looks like this is still missing @jasonaebischerGIT

**Pull request merged**
