### PR TITLE
[translate] Fix handling of complex-valued WCs in translation to EOS WET basis.

### PR DESCRIPTION
**Pull request by dvandyk**
Following changes to the EOS WET basis; see PR #4 in wcxf/wcxf-bases.

### CODE REVIEW

**Comment by dvandyk** [comment]
Can somebody tell me why this suddently does not work? I copied the code, literally, from one line to another...

**Comment by dvandyk** [comment]
Apparently Python is fine with arbitrary indentations in multiline statements within the right-hand side of a dict's key/value pair, but not for an assignment. Parentheses to the rescue!

@DavidMStraub I think merging this requires merging the wcxf-bases one first. Correct?

**Comment by dvandyk** [comment]
@peterstangl can you review and merge this please?

**Comment by DavidMStraub** [comment]
I added @jasonaebischerGIT as repository admin now. I can also merge it, but didn't have time to look at it...

**Comment by dvandyk** [comment]
@DavidMStraub ah, ok! I thought Peter had also taken over maintaining ```wilson```. Can I suggest to present the contact details of the maintainer on the project's ```README.md```?

**Comment by dvandyk** [comment]
@jasonaebischerGIT @DavidMStraub I have added to changes to the README. First, referring to the Stoffer/Dekens 1-loop paper. Second, mentioning that Jason is the maintainer of the package.

**Comment by DavidMStraub** [comment]
We haven't actually discussed that so far :thinking: 

Let's leave the Readme change separate from this FFTB.

**Comment by dvandyk** [comment]
Fine by me. Reverted to the old branch.

**Comment by dvandyk** [comment]
@jasonaebischerGIT ping!

**Comment by DavidMStraub** [comment]
Can be merged I think.

**Comment by jasonaebischerGIT** [comment]
Sorry, I did not get the notifications, since my tum mail does not work anymore. Can be merged, yes.

**Comment by dvandyk** [comment]
@jasonaebischerGIT excellent, but I cannot merge it! :-)

**Comment by jasonaebischerGIT** [comment]
I am not sure how. I don't think I am admin yet....

**Comment by DavidMStraub** [comment]
grafik

I'll try cancelling the invite and sending it out again. Please check your spam folder in case.

In the meantime I'll merge this.

**Comment by dvandyk** [comment]
Thanks David!

**Comment by jasonaebischerGIT** [comment]
Thanks David, I think it works now!

**Pull request merged**
